name: automerge

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    uses: RobinCombrink/actions-automerge/.github/workflows/automerge.yml@5f9734d8dcd96cf94ad1a41c6fa0171df8d367b7 # v1.0.3
