name: conventional-commits

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    uses: RobinCombrink/actions-conventional-commits/.github/workflows/conventional-commits.yml@7d25960f2e000f6f4535617f9f55f7eb27b00446 # v1.0.7
