name: gitleaks

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  scan:
    uses: RobinCombrink/actions-gitleaks/.github/workflows/gitleaks.yml@01dce36d3aa3cde80b8e1e8c2026da421dde881b # v1.0.3
