name: release

on:
  push:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: release

jobs:
  release:
    uses: RobinCombrink/actions-release/.github/workflows/release.yml@5b4c556bff4fbdaf8b42ab6f096ccf06fa095e90 # v1.0.3
