name: release

on:
  push:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: release

jobs:
  release:
    uses: RobinCombrink/actions-release/.github/workflows/release.yml@1e02c35d40602bf9ebb0eed1615aec89f2e6a5f7 # v1.2.0
